name:                raft
version:             0.1.0.0
github:              "hmac/raft"
license:             BSD3
author:              "Harry Maclean"
maintainer:          "harryjmaclean@gmail.com"
copyright:           "2018 Harry Maclean"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/hmac/raft#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- lens
- binary
- safe
- logging-effect
- text

library:
  source-dirs: src

executables:
  raft:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raft
    - distributed-process
    - network-transport-tcp

tests:
  integration:
    main:                Integration.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raft
    - hspec
  unit:
    main: Unit.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raft
    - hspec
