name:                raft
version:             0.1.0.0
github:              "hmac/raft"
license:             BSD3
author:              "Harry Maclean"
maintainer:          "harryjmaclean@gmail.com"
copyright:           "2018 Harry Maclean"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/hmac/raft#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- unordered-containers
- hashable
- lens
- binary
- safe
- text
- random
- monad-logger

library:
  source-dirs: src

executables:
  http:
    main:               Main.hs
    source-dirs:        app/http
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raft
    - bytestring
    - servant-server
    - servant-client
    - aeson
    - warp
    - http-client
    - time
    - optparse-applicative
    - dhall
    - stm

tests:
  integration:
    main:                Main.hs
    source-dirs:         test/integration
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raft
    - hspec
  unit:
    main:                Main.hs
    source-dirs:         test/unit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raft
    - hspec
    - unordered-containers
